### ISSUE TITLE
Bug: `/login` Internal Server Error

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#133]
Just tried the shiny **`Login`** button on the app: https://phoenix-chat.fly.dev/
<img width="684" alt="image" src="https://user-images.githubusercontent.com/194400/205891876-65929b0c-fe70-4009-bf44-5ee32e7f1a7c.png">

https://phoenix-chat.fly.dev/login
<img width="684" alt="image" src="https://user-images.githubusercontent.com/194400/205891684-d34bc7ae-0a4d-4bb2-b282-b348aaf620bb.png">

# Todo

+ [ ] investigate why this is happening
+ [ ] Document the fix
+ [ ] Deploy it!

**Comment by ndrean** [comment]
Meanwhile, a quick workaround (but not at all a fix):

```elixir
# chat_web/auth_controller.ex

def login(conn, _params) do
    try do
      redirect(conn, external: AuthPlug.get_auth_url(conn, "/"))
    rescue
      _e in FunctionClauseError ->
        redirect(conn, to: "/")
    end
end
```
Maybe the DB should also be cleaned...

**Comment by nelsonic** [comment]
Luckily, it's an easy fix. 
Visting https://fly.io/apps/phoenix-chat/secrets we see that the **`AUTH_API_KEY`** secret (Environment Variable) is not set:

<img width="2124" alt="image" src="https://user-images.githubusercontent.com/194400/205936611-048176c5-d894-49c0-9230-ac8130ceae27.png">

Docs ref: https://fly.io/docs/reference/secrets/#setting-secrets

1. Visit: https://authdemo.fly.dev/apps/new
2. Create app.
3. Export the secret:

```sh
flyctl secrets set AUTH_API_KEY=88SwQE3rB7oiK3HFgeZSmscEU4C2etc../authdemo.fly.dev
```

`fly` _automatically_ redeploys the app when a new secret is added:

```sh
Release v7 created
==> Monitoring deployment

 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
--> v7 deployed successfully
```

Confirmed there:
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/194400/205937284-067b561e-962a-45dc-8e38-4b6870fc8242.png">

Login/logout working:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/194400/205937626-15cbe133-5830-462f-b15a-18997a7cc6d4.png">

Done. ✅

**Comment by ndrean** [comment]
NB : I said "clean DB" not for this pb but because of the messaegs I saw !

**Comment by nelsonic** [comment]
Ah, Yes. People being rude. 🙄🤦‍♂️

**Comment by ndrean** [comment]
Yes... 
and the `try..rescue` was precisely because of:
```
[error] ERROR: AUTH_API_KEY Environment Variable is not set
```

**Comment by nelsonic** [comment]
@ndrean are you still seeing errors? 💭
