### ISSUE TITLE
Could you add Phoenix Presence?

### ISSUE THREAD

**Issue by ericridgeway** [dwyl/phoenix-chat-example#14]
This tutorial is so fantastic. Thanks lots. Are you able to add phoenix presence to the user name parts, to maybe keep a list of everyone who's connected and show when they disconnect and stuff?

Thanks again for wonderful guide!

**Comment by nelsonic** [comment]
@ericridgeway _great_ question/suggestion! Thank you for opening this issue. 🎉

**Comment by nelsonic** [comment]
@LuchoTurtle want to create a `presence.md` file and add "Who is online?" 🤭 
This should work for `anon1` and be updated to whatever name they pick in the chat. 👤 
And should _also_ reference the `person` if they have authenticated. 🔒
