### ISSUE TITLE
Add more clarity on the Travis CI part?

### ISSUE THREAD

**Issue by ericchuawc** [dwyl/phoenix-chat-example#15]
Just a suggestion

I have to google a bit to get this worked

1. Clone a copy of test.exs to config/travis.exs

2. In the travis.exs, make sure the password is set to "" (no password) for Postgres as per Travis docs

3. In travis.yml, my version is this

```
language: elixir
elixir:
  - 1.7.3
addons:
  postgresql: '9.5'
services:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
env:
  - MIX_ENV=test
script:
  - mix test
```
Hope it helps :)

Probably is good to mention that not all postgresql version can work with travis e.g. my local mac is using 10.5 but travis can't seem to support 10.5, have to use 9.5.

**Comment by nelsonic** [comment]
@ericchuawc thanks for sharing this. We have been using Postgres **`9.5`** ever since. 👍
