### ISSUE TITLE
Bug: Auth Not Working! - `Client_id not valid`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#150]
Just tried to authenticate by clicking the `Login` button on: https://phoenix-chat.fly.dev
Got the following:

<img width="923" alt="image" src="https://user-images.githubusercontent.com/194400/216372374-cef620ae-c802-4bb1-bb0d-03a04be76f34.png">

Please investigate! 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle do you have access to the `authdemo` app on Fly.io and the `phoenix-chat` to debug this? 💭 
If not, please LMK and I will add you. (sorry I don't have Fly.io open right now to check ...)

**Comment by LuchoTurtle** [comment]
I'll look into it.

**Comment by nelsonic** [comment]
Thanks. I think it will make sense to get this working ***`before`*** doing the update #149 
to ensure that we _know_ it's working. 👌

**Comment by LuchoTurtle** [comment]
`Fly.io` logs show the following.

```
GET / > auth_client_id: 88SwQE3rB7oiK3HFgeZSmscEU4C2ggqraUCyyxepZi8xj5WLzBBR, msg: auth_client_id: 88SwQE3rB7oiK3HFgeZSmscEU4C2ggqraUCyyxepZi8xj5WLzBBR is not valid index in auth controller, referer: https://phoenix-chat.fly.dev/ person:6
```

**Comment by LuchoTurtle** [comment]
Trying to get https://github.com/dwyl/auth to work but no luck. Even after setting up the `ADMIN_EMAIL` env, I keep getting this error:

`** (ArgumentError) construction of binary failed: segment 2 of type 'binary': expected a binary but got: nil`

**Comment by nelsonic** [comment]
Sorry, I should have been clearer. It's just the key that is invalid. This is a 1 minute fix:

Goto: https://authdemo.fly.dev/apps/10 and copy the `AUTH_API_KEY` variable.

Then following the instructions in: https://fly.io/docs/reference/secrets/ run the command:
```sh
flyctl secrets set AUTH_API_KEY=88Sabcdetc./88Setc./authdemo.fly.dev
```

Output:
```sh
Release v20 created
==> Monitoring deployment
Logs: https://fly.io/apps/phoenix-chat/monitoring

 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
--> v20 deployed successfully

```

Working:

https://user-images.githubusercontent.com/194400/216539650-4284c7a6-3618-44be-a80f-d6ed3ffaff6a.mov


But that UI bug at the bottom of the page is bugging me: https://github.com/dwyl/phoenix-chat-example/issues/151 Please fix! 🙏

**Comment by LuchoTurtle** [comment]
I changed the secret through Github secrets, shouldn't it have worked?

**Comment by nelsonic** [comment]
Changing the **secret** on `GitHub` will only affect the `CI`; the key will not be deployed/updated to `Fly.io`. 
Invalid `client_id` just means the `AUTH_API_KEY` is invalid. 
So updating it on `Fly.io` was my logical/immediate response.
