### ISSUE TITLE
Github action "deploy" failed

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-chat-example#154]
![image](https://user-images.githubusercontent.com/6057298/217278437-360810bc-0641-4145-a71f-6a4d5945ac8c.png)

I think the update to Phoenix 1.7 PR broke the deployment process, maybe missing files or configuration?
see https://github.com/dwyl/phoenix-chat-example/actions/runs/4114809002

**Comment by SimonLab** [comment]
> Step 22/37 : COPY rel rel
Error failed to fetch an image or build from source: error building: error rendering build status stream: COPY failed: file not found in build context or excluded by .dockerignore: stat rel: file does not exist

Indeed the `rel` folder has been removed on the PR https://github.com/dwyl/phoenix-chat-example/pull/152/files

![image](https://user-images.githubusercontent.com/6057298/217280549-06e2c758-448b-4f7e-9943-b2bf888613ba.png)

Looking at how to recreate this folder and add to Github for the action to be able to run.

**Comment by SimonLab** [comment]
Running `mix release.init`:
![image](https://user-images.githubusercontent.com/6057298/217282095-ecd97d63-c575-424c-a6eb-beba15652925.png)

However the files created are different from the ones deleted in the PR.
I'm going to copy the deleted file and add them back, hopefully this will fix the deployment issue.

**Comment by nelsonic** [comment]
Thanks @SimonLab I was literally just opening this exact issue ... 😉

**Comment by nelsonic** [comment]
Should be fixed by #155 🤞

**Comment by nelsonic** [comment]
https://github.com/dwyl/phoenix-chat-example/actions/runs/4115854000/jobs/7105174177#step:4:1356
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/194400/217301753-5d3e3048-39d9-48dd-b78e-1c1f6b134643.png">

Quick way to fix this is simply to rename the migration file.

**Comment by nelsonic** [comment]
PR: #157 assigned to @SimonLab 👌

**Comment by SimonLab** [comment]
Finally deployed!

**Comment by nelsonic** [comment]
Nice one. thanks @SimonLab 🙌
