### ISSUE TITLE
[Bug] Footer is not sticky to the bottom

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/phoenix-chat-example#158]
The footer is not sticky to the bottom of the page.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/17494745/217915434-73a86054-b214-4099-8e60-c482dcab765f.png">

If there are no messages, the footer gets "pulled up".

**Comment by nelsonic** [comment]
Thanks for opening this @LuchoTurtle 👍
