### ISSUE TITLE
Deploy to Gigalixir?

### ISSUE THREAD

**Issue by jesseshieh** [dwyl/phoenix-chat-example#17]
This repo is amazing!! Very well done! What do you think about adding a guide for deploying with Gigalixir? Disclaimer: I'm the founder of Gigalixir.

**Comment by nelsonic** [comment]
@jesseshieh Yeah, we _love_ the work you are doing with Gigalixir. 🎉 
If you have time to create a short guide as a Pull Request we would gladly merge it. 👍

**Comment by jesseshieh** [comment]
Awesome! I'll start writing one up.

**Comment by jesseshieh** [comment]
@nelsonic, so I started writing this up and realized it's pretty much going to be identical to https://gigalixir.readthedocs.io/en/latest/main.html#getting-started-guide. Do you think it would make more sense to just link to that and/or the [screencast](https://gigalixir.readthedocs.io/en/latest/main.html#screencast) instead?
