### ISSUE TITLE
Text Output Strange

### ISSUE THREAD

**Issue by MyBigNurse** [dwyl/phoenix-chat-example#18]
Hi - sorry, this is probably a silly question because this is my first time w/ Elixir but i followed this example and the output is weird in that each time a user enters an output it puts the output adjacent (rather than below with a line break), which makes the messages impossible to read... For example a typical output on my end looks like:

Bob hi there.  Alice Hello How are you?  Bob I'm good, and you?  Alice I'm good and you.

Maybe this is intended but ideally I would like the output to read as so (I believe with <br></br> line break or something of the sort) - 

Bob hi there.  
Alice Hello How are you?  
Bob I'm good, and you?  
Alice I'm good and you.

Now I thought the code that controlled this was app.js.  I'm no expert with JS, but I tried every possible iteration of adding in a line break into channel.on as well as msg.addEventListener ... and no matter what the line breaks don't appear to show up in the code (not sure if this is because they are getting wrapped inside "li.. /li" elements).

Could you please suggest how to adjust this so that every record from the DB is separated with a line break?

I thought something like the following addition of a "br" element would work, but it does not - 

channel.on('shout', function (payload) {
  var li = document.createElement("li");
  var name = payload.name || 'guest';
  li.innerHTML = '<p><b>' + name + '</b>: ' + payload.message + '</p> <br />';
  ul.appendChild(li);
  ul.appendChild(document.createElement("br"));
});

**Comment by MyBigNurse** [comment]
Also, thanks btw for posting this example.  I thought it was quite interesting!

**Comment by nelsonic** [comment]
@MyBigNurse this appears to be a CSS bug. thank you for reporting it. 👍

**Comment by MyBigNurse** [comment]
Thanks, Nelson. Sorry but I don’t know much about how css works in elixiror what exactly this app.css ref is doing. Do you have a suggestion on what file I need to look at to try and fix it? Is it in the app.css file? Thanks for your reply

**Comment by nelsonic** [comment]
@MyBigNurse yeah, **app.css** should be a good place to start.
@Cleop or @RobStallion might be able to help.
Can you upload a screenshot of what you are seeing?

**Comment by MyBigNurse** [comment]
<img width="1076" alt="horizontalchat results" src="https://user-images.githubusercontent.com/45836584/50034184-a1088680-ffc9-11e8-92ee-6a730f95a0d3.png">

**Comment by MyBigNurse** [comment]
> @MyBigNurse yeah, **app.css** should be a good place to start.
> @Cleop or @RobStallion might be able to help.
> Can you upload a screenshot of what you are seeing?

Thanks guys - just uploaded a screenshot of what it looks like.

**Comment by MyBigNurse** [comment]
So I opened up chat/priv/static/css/app.css and I removed the following section of code.

The first line of code in the CSS file looks like:

*,*:after,*:before{box-sizing:inherit}html .... 

And it is this super massive and impossible to read entry of css.  By randomly deleting sections i was able to see that removing the following text:

"{display:inline}.label-inline{display:inline-block;font-weight:normal;margin-left:.5rem}"

that this appears to fix the problem of centering entries. However, a few questions about this.  First, while removing this little snippet appears to fix the problem, I'm not sure where this section begins or ends, and not sure if removing just this little part (and not a longer portion) is not breaking something else in the CSS.

Secondly, can someone explain how this massive statement in the CSS was generated in the first place?  Is there some tool that was used for building this?  Because I cannot imagine anyone wrote this line of code by hand (it seems far to long to have been manually generated).  It would just be helpful to know how this CSS is being created so that I can make my own CSS file.

**Comment by RobStallion** [comment]
@MyBigNurse could you create a repo that you could push this code to? It would be helpful if I could look at your code as I cannot replicate your error in the demo version. 

If you could also comment letting us know what browser you are using that would be helpful. 👍

**Comment by LatitudeAdjustment** [comment]
This is a CSS issue.
Phoenix 1.4 now includes Milligram for styling, not Bootstrap as in previous versions.  So, a newly generated project will not work like the one in the repo.
The template in Step 3 will have to be modified accordingly for Milligram.
Also Webpack is now used instead of Brunch for handling static assets.

**Comment by LatitudeAdjustment** [comment]
I was able to improve the output by removing "class='row'" from line 2 in index.html.eex.

`<ul id='msg-list' class='row' style='list-style: none; min-height:200px; padding: 10px;'>`

to

`<ul id='msg-list' style='list-style: none; min-height:200px; padding: 10px;'>`

**Comment by nelsonic** [comment]
Updated in:
https://github.com/dwyl/phoenix-chat-example/blob/7a097643aa5b05e04321687ea6c169007a99e148/lib/chat_web/templates/page/index.html.eex#L2-L3

Thanks again @LatitudeAdjustment  🥇
