### ISSUE TITLE
This article isn't really geared for Phoenix 1.4?

### ISSUE THREAD

**Issue by ericchuawc** [dwyl/phoenix-chat-example#19]
Just my personal feedback.

As it is stated it will be based on Phoenix 1.4, some parts are not so applicable

Examples

npm install in assets folder, believed this is no longer valid as phoneix 1.4 is using webpack and npm install will work when you setup the project for the 1st time

also phoenix 1.4 is using milligram, so the codes in index.html.eex will not display properly as the codes are based on bootstrap related.

Hope you can enhance it or have a change notes somewhere. It will help the beginners to phoenix 1.4.

**Comment by nelsonic** [comment]
@ericchuawc _thank you_ for your feedback. ❤️ 
We would _gladly_ accept a pull request with any updates 
which you feel are relevant to make the example more applicable to **Phoenix v.1.4**

**Comment by Marcos-Costa** [comment]
I've noticed bugs as well, mainly due to the bootstrap change. I'll fix it an send a pull request as soon as I can.

**Comment by nelsonic** [comment]
Long since updated to Phoenix 1.5.5 #48 with complete review. 
Update to 1.6 on Todo List for soon. #55 
Closing.
