### ISSUE TITLE
Speed Run! 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#255]
Hi @MikeRund, 👋 
please _speed-run_ the tutorial in this repo and `try` to spot the areas where there are any gaps in the instructions. 👀 
If you get stuck, comment in this issue thread or open specific issues for the challenges/obstacles you see. 🙏 

If you get stuck because of using [`Windows`](https://github.com/dwyl/dev-setup/issues/66) please let us know. 💬 
We've not had anyone `else` report issues using `Windows` in the past, but it's always good to know if there are obstacles. 👌

**Comment by nelsonic** [comment]
@MikeRund did you get as far as the `auth` section? [/auth.md](https://github.com/dwyl/phoenix-chat-example/blob/main/auth.md) ? 🔐

**Comment by MikeRund** [comment]
Not-so "speed" run but all complete now.. 😯 Took a thorough run through and added instructions / made changes throughout the readme, auth.md and presence.md.

**Comment by nelsonic** [comment]
Yeah, don't worry about the time taken. 😉 
As long as you went through everything and understood it you're golden. 🥇 
On to the next one! ⏭️
