### ISSUE TITLE
Pending migrations for repo error

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-chat-example#258]
When adding the code to integrate `Postgres` I'm met with the following error:

```sh
Phoenix.Ecto.PendingMigrationError at GET /
there are pending migrations for repo: Chat.Repo.
Try running `mix ecto.migrate` in the command line to migrate it
```

My messages table looks the same as the setup image in `pgAdmin`
(i.e. I've already set up and run ecto.migrate), and the code is the same as the readme. 
If I run mix ecto.migrate as the error suggests I run into a duplication error.

It seems that my code is trying to make a new table instead of inserting into the current. Any ideas?

**Comment by nelsonic** [comment]
Seems like there is a migration file in your `/priv/repo/migrations` that has not been run. 🤔 
Consider running `mix ecto.reset` and confirm if this is still an issue. 🤞

**Comment by MikeRund** [comment]
Worked a treat! And now the version number is the same in the schema_migrations table  in postgres and `/priv/repo/migrations`. Thanks!
