### ISSUE TITLE
Doesn't work as is, get "unable to join: unmatched topic" error

### ISSUE THREAD

**Issue by ericridgeway** [dwyl/phoenix-chat-example#29]
You forgot the step where you need to change socket.js to use
`let channel = socket.channel("room:lobby", {})`
instead of 
`let channel = socket.channel("topic:subtopic", {})`

**Comment by nelsonic** [comment]
@ericridgeway _thank you_ for opening this issue! (_glad someone was paying attention_)
If you have time to create a pull request fixing the docs, please do.

**Comment by nelsonic** [comment]
I have added instructions to section 4.1: https://github.com/dwyl/phoenix-chat-example/tree/comment-topic-subtopic-issue%2329#41-comment-out-lines-in-socketjs so people will not see the error.

@iteles please see: #33 (_thanks!_) 🌻
