### ISSUE TITLE
Many thanks for this sweet example ;)

### ISSUE THREAD

**Issue by AleksandarFilipov** [dwyl/phoenix-chat-example#34]
That's it, keep up the good work!

**Comment by nelsonic** [comment]
@AleksandarFilipov glad you found it useful. Thanks for your feedback! 🥇 
We will be extending it soon to include _several_ new features. Stay tuned. 😉

**Comment by AleksandarFilipov** [comment]
Thats great! I use the inspiration in an umbrella. Could be a suggestion for comig features. Looking forward for updates. 
Cheers

**Comment by nelsonic** [comment]
@AleksandarFilipov If you find a **good tutorial** for **umbrella apps**, **please _share_ links**! 🙏  
(_we have never found one that we thought was particularly beginner-friendly..._) 🙄

**Comment by AleksandarFilipov** [comment]
I did find this useful to some extent https://cultivatehq.com/posts/elixir-distillery-umbrella-docker/

**Comment by nelsonic** [comment]
@AleksandarFilipov thanks for sharing. (Added to reading list) 🙌

**Comment by AleksandarFilipov** [comment]
I suggested that we should go through your example at the elixir meetup in malmö/sweden (we don't have a date for next meetup yet). @nelsonic if you are around you could be the presenter :)

**Comment by nelsonic** [comment]
once again, you're very welcome. ❤️ 
it's the example we _wished_ existed when we started learning `Elixir/Phoenix`. 🙏 
And it will soon be updated to the latest version: #149 🚀 

Closing as no further action required on this issue. ✅
