### ISSUE TITLE
Did not get expected result at step 8.1 - Review the Messages Table Schema

### ISSUE THREAD

**Issue by linovate** [dwyl/phoenix-chat-example#35]
I am following this tutorial step by step. At step 8.1 - Review the Messages Table Schema, I could not see any table created thru psql cli tool . If the table is created, I should be able to see it through either pgAdmin or CLI, is that right?   

I am using Phoenix 1.4.11 instead of 1.4.4 if that might be the reason. 

Could you shed some light on how to  create the table ?

Thanks ! This is a fantastic tutorial for beginners !

**Comment by linovate** [comment]
FYI, I try to go through the tutorial again, using Phoenix 1.4.4, I got following error at step 6 (upon  running mix ecto.create):

05:56:11.202 [error] GenServer #PID<0.344.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
    (db_connection) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Chat.Repo couldn't be created: killed

**Comment by nelsonic** [comment]
@linovate thanks for opening this issue. it's always good to know that people find it. 👍 
It appears as though your Phoenix App is not able to connect to the Postgres database. 
Can you please confirm:
+ What operating system you are using?
+ Did you change the default password for your Postgres?
  + If so, did you remember to update it in your [`config/dev.exs`](https://github.com/dwyl/phoenix-chat-example/blob/master/config/dev.exs#L61) file? 

If Phoenix is unable to _connect_ to Postgres then the `mix ecto.create` and `mix ecto.migrate` won't work.

**Comment by nelsonic** [comment]
No response from OP. Presume that they figured out how to run the app after updating their config. 
Closing.
