### ISSUE TITLE
Have some problems on step 5

### ISSUE THREAD

**Issue by vagrabar** [dwyl/phoenix-chat-example#36]
After printing "cd assets && npm install && cd .." (or anything else instead "..") it writes me: 
mac:chat mac$ cd assets && npm install && cd .. //First try
-bash: npm: command not found
mac:assets mac$ cd assets && npm install && cd .. //Second try
-bash: cd: assets: No such file or directory

**Comment by nelsonic** [comment]
@vagrabar please confirm you have `node.js` installed on your machine.
https://nodejs.org/en/download
It is required to compile the `JavaScript` for the Client. 

As for not having the `/assets` directory, please confirm you created a new Phoenix App in step 1.
Your directory structure should match that of this repository.
**`/assets` should be at the root of your project.
You may have skipped a step. Can you please run the following commands:

Print working directory:
```
pwd
```
Are you you in a directory called `/chat` ? (_that was created in step 1_)

**Comment by vagrabar** [comment]
After printing a command from step 5 directory changed from chat to assets. Do I need to start making a project again?
After printing "pwd": /Users/mac/chat/assets

**Comment by vagrabar** [comment]
And, yes, I didn't have node.js on my machine. I have already installed it.

**Comment by vagrabar** [comment]
Restarted making chat and after installing node.js package everything works.

**Comment by nelsonic** [comment]
@vagrabar sounds good. Hope you manage to finish working your way through the tutorial. 👍 
If this has resolved your issue, please remember to close the issue. ✅ 
Thanks! 👋

**Comment by vagrabar** [comment]
![I have a question](https://user-images.githubusercontent.com/61086187/74591491-9d3b1e80-5029-11ea-9abf-885e38a149f1.jpeg)
Excuse-me, but after printing a command from step 5 I saw this message. What does it mean? Yes, here is another two messages, that I got after.

**Comment by nelsonic** [comment]
These NPM warnings are simply informing you that a couple of packages are out-of-date.
To run any **`npm`** command you need to be in the **`/chat/assets`** directory. 
So run `cd assets` and _then_ run `npm audit fix`

What version of Phoenix are you running? Run:
```sh
mix phx.new -v
```

**Comment by vagrabar** [comment]
v.1.4.4

**Comment by nelsonic** [comment]
Ok, that's why the `node.js` dependencies are out-of-date. It won't be an issue. 💭 
But you should be 100% fine to continue working on the example/tutorial. 👍

**Comment by vagrabar** [comment]
Ok, thank a lot. So, I think, it is the end of a problem :) I'm sorry for such stupid questions. Actually, it is my first project on GitHub that I make.

**Comment by nelsonic** [comment]
@vagrabar there are no "stupid questions". Especially for someone who is just starting out!
We're stoked you had the _courage_ to open a question even _risking_ looking "stupid".
We've all asked "noob" questions. That's the _only_ way to learn. Keep going! 🚀
