### ISSUE TITLE
Update to Phoenix 1.5.1

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#38]
With the recent release of **Phoenix 1.5** 🎉 https://elixirforum.com/t/phoenix-v1-5-0-released/30693
Now is a _great_ time to go through this example/tutorial with a fresh pair of eyes and _completely_ update it (_including_) links to code snapshots. We can also _extend_ it to include **`auth_plug`** #25 🔐 and **presence** #32 🚀.

+ [x] Checkout `master` 
+ [x] Create new branch e.g: `update-to-phoenix-1.5-issue#38`
+ [x] ***`DELETE`*** _all_ the code (_so we can start from scratch!_)
+ [x] Go through the example step-by-step from the `mix phx.new chat` all the way to the end!
  + [x] Update/rewrite any sections that need to be updated following the **upgrade guide**:
      https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f
      https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md
+ Bonus: #54
+ **Bonus Level 2**: Add **Presence** #32 to show who is online.

Related to #19 (feedback on the version of the tutorial).

I expect this to take around **4 hours**. ⏳ 
@SimonLab / @iteles if you want to remote-pair on this, LMK. 👍 
Testing **`auth_plug`** and ***Presence*** are both core to our App "roadmap". 🗺️

**Comment by nelsonic** [comment]
New Phoenix Home Page:
![image](https://user-images.githubusercontent.com/194400/82494801-11caa100-9ae2-11ea-821d-8181580201cb.png)

**Comment by nelsonic** [comment]
Update UI:
![image](https://user-images.githubusercontent.com/194400/82498454-ef3b8680-9ae7-11ea-9d1f-8cf593deacba.png)

**Comment by nelsonic** [comment]
Update in progress: #39 
https://github.com/dwyl/phoenix-chat-example/tree/update-to-phoenix-1.5-issue%2338

**Comment by Leo328** [comment]
https://github.com/dwyl/phoenix-chat-example/issues/40

Thought I'd leave this here so it can go along with the updates.

**Comment by nelsonic** [comment]
The PR #39 (and #43) was merged with the update to Phoenix 1.5.3 🎉  (thanks @Simon & @iteles!)
It did not contain Auth or Presence. I still very much want to add these two enhancements.
Happy for _anyone_ else to add Auth as a test of the simplicity of https://github.com/dwyl/auth_plug while following https://github.com/dwyl/auth_plug_example#how

**Comment by nelsonic** [comment]
This was updated over a year ago. ✅ 
`GOTO`: #55 🆕
