### ISSUE TITLE
In case people can't determine if Postgresql is running with lsof -i :5432

### ISSUE THREAD

**Issue by Leo328** [dwyl/phoenix-chat-example#40]
Hi there,

This is my first ever open-source contribution post on GitHub.  I'm super-new at this but also want to make sure others don't get stuck with frustrating issues when learning.

I noticed that when going through the tutorial, there was a recommendation to use `lsof -i :5432` to check if Postgresql was running correctly.  This didn't work for me (there was no output), but I do know that Postgres was running as I had just successfully created a new DB with Ecto.

**Instead, I used `pg_isready` and got the desired confirmation:**

![image](https://user-images.githubusercontent.com/34203410/82743232-d82cbb00-9dab-11ea-80bc-c4c958bcca93.png)

For context, I am running Ubuntu 18.04 through WSL2 with Postgresql-12.

Cheers,
Leo.

**Comment by nelsonic** [comment]
@Leo328 great addition. 
```
pg_isready
/tmp:5432 - accepting connections
```
Works on Mac too. ✅

**Comment by nelsonic** [comment]
@LuchoTurtle please add the `pg_isread` command to the https://github.com/dwyl/phoenix-chat-example#check-you-have-everything-before-starting section during your update #149 🙏

**Comment by nelsonic** [comment]
Just tried to run:
```sh
pg_isready
```
On my `M1` mac and ...

Got:

```sh
zsh: command not found: pg_isready
```

**Comment by LuchoTurtle** [comment]
Weird that it was working on your Mac prior and not anymore.
It comes with [`psql`](https://command-not-found.com/pg_isready), weird that you get a `not found` error.

**Comment by nelsonic** [comment]
Yeah, thought it was weird too… hence capturing in case anyone else faces this in the future … ⏳
