### ISSUE TITLE
Issue with "coveralls" with ElixirLS

### ISSUE THREAD

**Issue by Leo328** [dwyl/phoenix-chat-example#41]
Hey there,

Not sure if this is an ElixirLS issue or an issue with the documentation, but in relation to [point 15](https://github.com/dwyl/phoenix-chat-example#user-content-151-add-excoveralls-as-a-development-dependency-to-mixexs) in the tutorial, I found the text placed in the dependencies folder throws a syntax error

![image](https://user-images.githubusercontent.com/34203410/82747743-9c134d80-9ddf-11ea-8cfd-8e4852cf909d.png)

I ended up removing the `""` from the first elements and ElixirLS is happy with this.  I'm totally new to this so I'm not sure whether or not this is expected.

Additionally, in my case, `excoveralls 0.7.5` appears to have been included previously.

```
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  certifi 2.5.1
  connection 1.0.4
  cowboy 2.7.0
  cowlib 2.8.0
  db_connection 2.2.2
  decimal 1.8.1
  ecto 3.4.4
  ecto_sql 3.4.4
  excoveralls 0.7.5
  exjsx 4.0.0
  file_system 0.2.8
  gettext 0.18.0
  hackney 1.15.2
  idna 6.0.0
  jason 1.2.1
  jsx 2.8.3
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  parse_trans 3.3.0
  phoenix 1.5.3
  phoenix_ecto 4.1.0
  phoenix_html 2.14.2
  phoenix_live_dashboard 0.2.4
  phoenix_live_reload 1.2.2
  phoenix_live_view 0.13.0
  phoenix_pubsub 2.0.0
  plug 1.10.1
  plug_cowboy 2.2.1
  plug_crypto 1.1.2
  postgrex 0.15.4
  ranch 1.7.1
  ssl_verify_fun 1.1.5
  telemetry 0.4.1
  telemetry_metrics 0.5.0
  telemetry_poller 0.5.0
  unicode_util_compat 0.4.1
All dependencies are up to date
```

**Comment by nelsonic** [comment]
Hi @Leo328, Thanks for opening this issue to share your experience!
We're *stoked* that you've found this tutorial and are going through. 🎉 
In the `mix.exs` file the keyword "coveralls" does not need the quotes around it,
you should only see a `warning` for that, and it's safe to remove the quotes.

These will be removed in #39 to avoid any further confusion for people following the tutorial. 👍

**Comment by nelsonic** [comment]
Hopefully this is resolved now so closing. Please re-open if required. 👍
