### ISSUE TITLE
The database for Chat.Repo couldn't be created: killed

### ISSUE THREAD

**Issue by AaronLain** [dwyl/phoenix-chat-example#49]
Hey all! I have been trying to get the full version of this running before building it out. Postgres installed flawlessly and I got it up and running without an issue. I followed the initial instructions/installations then git-cloned and ran mix install but keep running into this error:

2020-10-17 18:05:27.473 CDT [3405] FATAL:  role "postgres" does not exist

18:05:27.473 [error] GenServer #PID<0.3651.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
    (db_connection 2.3.0) lib/db_connection/connection.ex:99: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Chat.Repo couldn't be created: killed

I ran a mix.update -all since I noticed that postgrex wasn't the absolute latest version, but I'm still getting the same error. I'm very new to elixir so I'm a bit stumped.

Edit: I'm running Mac OSX Catalina 10.15.7

**Comment by ondrej-tucek** [comment]
Check the AstonJ [post](https://elixirforum.com/t/mix-ecto-create-errors-with-role-postgres-does-not-exist/20624) or Sears's article [Getting Started with PostgreSQL on Mac OSX](https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb) :eyes:

**Comment by nelsonic** [comment]
Yeah, that getting started guide should help you make progress. 💡 
If not, please share _how_ you installed Postgres; e.g. using `brew` or https://postgresapp.com ?

**Comment by AaronLain** [comment]
I installed via brew as per the instructions. I will say I had an old installation via the app, but uninstalled it (via the provided uninstall.pkg) before using the brew method to prevent any sort of issue. Maybe I messed up there?

**Comment by AaronLain** [comment]
> Check the AstonJ [post](https://elixirforum.com/t/mix-ecto-create-errors-with-role-postgres-does-not-exist/20624) or Sears's article [Getting Started with PostgreSQL on Mac OSX](https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb) :eyes:
> 
> 
I will read the AstonJ post when I get home, but that might be the issue. I'll update as soon as I can.

**Comment by AaronLain** [comment]
@nelsonic you are my hero. I must have missed that post in my googling. Going to have to check the elixir forums more often! 

[Solution](https://elixirforum.com/t/mix-ecto-create-errors-with-role-postgres-does-not-exist/20624) for the curious.

Going to close this issue. Thanks for the quick responses.

**Comment by nelsonic** [comment]
@AaronLain I'm not the hero here. @ondrej-tucek is for sharing that helpful link. 🔗 😉 
Glad you got it working. 🚀 
If you find this tutorial/example useful, please ⭐ it to help others find it. 🙌

**Comment by ondrej-tucek** [comment]
You're welcome Aaron. I'm glad to hear you that was helpful. Nice day :sunny:
