### ISSUE TITLE
Possible readme update

### ISSUE THREAD

**Issue by parkhabit** [dwyl/phoenix-chat-example#5]
As a first time Pheonix user I followed the **Step 1** in the readme and created the app, but when checking to see if I had done it properly I received the following error message numerous times, filling my terminal. 
```
[error] Postgrex.Protocol (#PID<0.363.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name): database "chat_dev" does not exist
```
I understand that the site works correctly as shown in the demo and that this error occurred as I had not created my database yet. However, I wasn't expecting to see a terminal full of errors and I thought it may put some newer users off. 

Perhaps you could consider moving **Step 6 Create/Configure Database** into **Step 1** Or noting that when starting the server there will be errors and the reason for them at this time.

**Comment by nelsonic** [comment]
@parkhabit _great_ point!  (_**thank you** for taking time to open this issue_) 
we could re-jig the tutorial to instruct people to `mix ecto.create` sooner
or _advise_ that there will be errors in the terminal until the DB is created ...
What is _your_ preference?

**Comment by shirleymiao** [comment]
Just ran into this as well. The easiest fix is probably to advise that there will be errors in the terminal until the DB is created!

**Comment by iteles** [comment]
@shirleymiao Thanks for commenting and for letting us know! We'd very much welcome a pull request to that effect if you're up for it 😊

**Comment by nelsonic** [comment]
Readme recently & comprehensively updated to _latest_ `Phoenix` by @LuchoTurtle in https://github.com/dwyl/phoenix-chat-example/pull/113 🎉 ✅
