### ISSUE TITLE
Heroku Build/Start Failing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-chat-example#65]
@SimonLab thanks for reporting that you were seeing an Application Error for the app ... https://phxchat.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/137934741-ee24162b-70ed-47d7-a0f9-80c2b099995a.png)

The logs suggest we are missing a dependency on `hackney`: https://dashboard.heroku.com/apps/phxchat/logs
![image](https://user-images.githubusercontent.com/194400/137934620-0decfabe-406a-4243-9d24-ec489a47bff0.png)

If you have time to investigate, please do. 
Otherwise I can take a look later today (_after work ..._)

**Comment by SimonLab** [comment]
Restarting Heroku gives the following message:
![image](https://user-images.githubusercontent.com/6057298/137939691-3c4329f2-f772-4561-8087-849dce8c6eb3.png)

**Comment by SimonLab** [comment]
The Phoenix logo is not displayed:
![image](https://user-images.githubusercontent.com/6057298/137983381-366f0b2e-a0bc-4803-90f3-893d23b14d23.png)

I've tried to run `mix assets.deploy` on Heroku but it didn't resolve the assets issue.
Also it might be another issue, at the moment the messages are not saved, ie if you refresh your page your "Seems to be working fine" won't appear anymore. I need o dive into the code to see if it's limit on the number of messages displayed or if the message itself is not saved

**Comment by ajmeese7** [comment]
@SimonLab that is the same issue I was experiencing a few days ago, rebuilding my environment and setting up the application again as you suggested fixed it for me. Maybe try that if you haven't already?

**Comment by nelsonic** [comment]
@ajmeese7 I think the issue Simon is seeing is legit. 
The logo is AWOL for me too on the Heroku app: https://phxchat.herokuapp.com/

<img width="1113" alt="phxchat-heroku-logo-404" src="https://user-images.githubusercontent.com/194400/138001905-03858e92-7a0d-4a2b-a584-00d0c984929d.png">

It might just be a case of re-building the app, but I think Simon has already tried that. 💭 


As for the new chat messages not being stored in the DB: there are only 1,327 rows used of the available 10,000.
https://data.heroku.com/datastores/5c9d21d3-7aac-4672-9697-272fcc1cfa3a
![image](https://user-images.githubusercontent.com/194400/138001642-7c703eca-29ef-4732-b4ab-d388e9f43af5.png)

So there must be an issue with writing from the App into the `Repo`. We may need to do some Logging to see why.
